// Packet
#define IPLAT_ERR_SUCCESS 0x01

#define IPLAT_ERR_SET_OPERATION_MODE 0xA0
#define IPLAT_ERR_CONNECT_AP 0xA1
#define IPLAT_ERR_DISABLE_MUX 0xA2
#define IPLAT_ERR_CONNECT_SERVER 0xA3

// REQC Error
#define IPLAT_ERR_REQC 0xA4

// Sensor number is not equared registered sensor number
#define IPLAT_ERR_NOT_MATCHED_SENSOR_NUM 0xE1

// Registered Sensors
#define IPLAT_ERR_NOT_REGISTERED_SENSOR_1 0xE2
#define IPLAT_ERR_NOT_REGISTERED_SENSOR_2 0xE3
#define IPLAT_ERR_NOT_REGISTERED_SENSOR_3 0xE4
#define IPLAT_ERR_ALL_REGISTERED_SENSORS 0xE0

#define IPLAT_SUCCESS_SEND_DATA 0xF0
#define IPLAT_ERR_SEND_DATA 0xF1
